package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.api.OwnableTileEntity;
import net.geforcemods.securitycraft.api.SecurityCraftTileEntity;
import net.geforcemods.securitycraft.containers.*;
import net.geforcemods.securitycraft.entity.*;
import net.geforcemods.securitycraft.items.ModuleItem;
import net.geforcemods.securitycraft.tileentity.*;
import net.geforcemods.securitycraft.util.HasManualPage;
import net.geforcemods.securitycraft.util.OwnableTE;
import net.geforcemods.securitycraft.util.RegisterItemBlock;
import net.geforcemods.securitycraft.util.RegisterItemBlock.SCItemGroup;
import net.geforcemods.securitycraft.util.Reinforced;
import net.minecraft.block.Block;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.entity.EntityType;
import net.minecraft.fluid.FlowableFluid;
import net.minecraft.item.Item;
import net.minecraft.screen.ScreenHandlerType;

public class SCContent { // TODO: Everything


    //fluids
    public static FlowableFluid FLOWING_FAKE_WATER;
    public static FlowableFluid FAKE_WATER;
    public static FlowableFluid FLOWING_FAKE_LAVA;
    public static FlowableFluid FAKE_LAVA;

    //blocks
    @HasManualPage @RegisterItemBlock public static Block ALARM;
    @HasManualPage(designedBy="Henzoid") @RegisterItemBlock public static Block BLOCK_POCKET_MANAGER;
    @HasManualPage @RegisterItemBlock(SCItemGroup.DECORATION) public static Block BLOCK_POCKET_WALL;
    @HasManualPage @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block BOUNCING_BETTY;
    @HasManualPage @RegisterItemBlock public static Block CAGE_TRAP;
    @RegisterItemBlock(SCItemGroup.DECORATION) public static Block CHISELED_CRYSTAL_QUARTZ;
    @HasManualPage @RegisterItemBlock(SCItemGroup.DECORATION) public static Block CRYSTAL_QUARTZ;
    @RegisterItemBlock(SCItemGroup.DECORATION) public static Block CRYSTAL_QUARTZ_PILLAR;
    @RegisterItemBlock(SCItemGroup.DECORATION) public static Block CRYSTAL_QUARTZ_SLAB;
    @HasManualPage @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block CLAYMORE;
    @HasManualPage @OwnableTE @RegisterItemBlock public static Block FRAME;
    @HasManualPage @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block IMS;
    @HasManualPage @RegisterItemBlock public static Block INVENTORY_SCANNER;
    public static Block INVENTORY_SCANNER_FIELD;
    @HasManualPage @RegisterItemBlock(SCItemGroup.DECORATION) public static Block IRON_FENCE;
    @HasManualPage @RegisterItemBlock public static Block KEYCARD_READER;
    @HasManualPage @RegisterItemBlock public static Block KEYPAD;
    @HasManualPage public static Block KEYPAD_CHEST;
    @HasManualPage @RegisterItemBlock public static Block KEYPAD_FURNACE;
    @HasManualPage @RegisterItemBlock public static Block LASER_BLOCK;
    public static Block LASER_FIELD;
    @HasManualPage @RegisterItemBlock public static Block MOTION_ACTIVATED_LIGHT;
    @HasManualPage @OwnableTE @RegisterItemBlock public static Block PANIC_BUTTON;
    @HasManualPage @RegisterItemBlock public static Block PORTABLE_RADAR;
    @HasManualPage @OwnableTE @RegisterItemBlock public static Block PROJECTOR;
    @HasManualPage @RegisterItemBlock public static Block PROTECTO;
    @OwnableTE public static Block REINFORCED_DOOR;
    @HasManualPage @RegisterItemBlock(SCItemGroup.DECORATION) public static Block REINFORCED_FENCEGATE;
    @HasManualPage @RegisterItemBlock public static Block RETINAL_SCANNER;
    public static Block SCANNER_DOOR;
    public static Block SECRET_OAK_SIGN;
    public static Block SECRET_OAK_WALL_SIGN;
    public static Block SECRET_SPRUCE_SIGN;
    public static Block SECRET_SPRUCE_WALL_SIGN;
    public static Block SECRET_BIRCH_SIGN;
    public static Block SECRET_BIRCH_WALL_SIGN;
    public static Block SECRET_JUNGLE_SIGN;
    public static Block SECRET_JUNGLE_WALL_SIGN;
    public static Block SECRET_ACACIA_SIGN;
    public static Block SECRET_ACACIA_WALL_SIGN;
    public static Block SECRET_DARK_OAK_SIGN;
    public static Block SECRET_DARK_OAK_WALL_SIGN;
    public static Block SECRET_CRIMSON_SIGN;
    public static Block SECRET_CRIMSON_WALL_SIGN;
    public static Block SECRET_WARPED_SIGN;
    public static Block SECRET_WARPED_WALL_SIGN;
    @HasManualPage @RegisterItemBlock public static Block SECURITY_CAMERA;
    @RegisterItemBlock(SCItemGroup.DECORATION) public static Block STAIRS_CRYSTAL_QUARTZ;
    @OwnableTE @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block TRACK_MINE;
    @HasManualPage @OwnableTE @RegisterItemBlock(SCItemGroup.TECHNICAL) public static Block TROPHY_SYSTEM;
    @HasManualPage @RegisterItemBlock public static Block USERNAME_LOGGER;
    @HasManualPage @OwnableTE @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block MINE;
    public static Block FAKE_WATER_BLOCK;
    public static Block FAKE_LAVA_BLOCK;

    //block mines
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block STONE_MINE;
    @HasManualPage @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block DIRT_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block COBBLESTONE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block SAND_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block GRAVEL_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block GOLD_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block IRON_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block COAL_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block NETHER_GOLD_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block LAPIS_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block DIAMOND_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block REDSTONE_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block EMERALD_ORE_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block QUARTZ_ORE_MINE;
    public static Block ACIENT_DEBRIS_MINE;
    @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block GILDED_BLACKSTONE_MINE;
    @HasManualPage @OwnableTE @RegisterItemBlock(SCItemGroup.EXPLOSIVES) public static Block FURNACE_MINE;

    //reinforced blocks (ordered by vanilla building blocks creative tab order)
    @HasManualPage(specialInfoKey="help.securitycraft:reinforced.info") @OwnableTE @Reinforced public static Block REINFORCED_STONE;
    @OwnableTE @Reinforced public static Block REINFORCED_GRANITE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_GRANITE;
    @OwnableTE @Reinforced public static Block REINFORCED_DIORITE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_DIORITE;
    @OwnableTE @Reinforced public static Block REINFORCED_ANDESITE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_ANDESITE;
    @OwnableTE @Reinforced public static Block REINFORCED_GRASS_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_DIRT;
    @OwnableTE @Reinforced public static Block REINFORCED_COARSE_DIRT;
    @OwnableTE @Reinforced public static Block REINFORCED_PODZOL;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_NYLIUM;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_NYLIUM;
    @OwnableTE @Reinforced public static Block REINFORCED_COBBLESTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_OAK_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_SPRUCE_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_BIRCH_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_JUNGLE_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_ACACIA_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_OAK_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_PLANKS;
    @OwnableTE @Reinforced public static Block REINFORCED_SAND;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_SAND;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAVEL;
    @OwnableTE @Reinforced public static Block REINFORCED_OAK_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_SPRUCE_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_BIRCH_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_JUNGLE_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_ACACIA_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_OAK_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_STEM;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_STEM;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_OAK_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_SPRUCE_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_BIRCH_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_JUNGLE_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_ACACIA_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_DARK_OAK_LOG;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_CRIMSON_STEM;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_WARPED_STEM;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_OAK_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_SPRUCE_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_BIRCH_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_JUNGLE_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_ACACIA_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_DARK_OAK_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_CRIMSON_HYPHAE;
    @OwnableTE @Reinforced public static Block REINFORCED_STRIPPED_WARPED_HYPHAE;
    @OwnableTE @Reinforced public static Block REINFORCED_OAK_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_SPRUCE_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_BIRCH_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_JUNGLE_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_ACACIA_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_OAK_WOOD;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_HYPHAE;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_HYPHAE;
    @OwnableTE @Reinforced public static Block REINFORCED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_LAPIS_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_CUT_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_WHITE_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_ORANGE_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_MAGENTA_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_BLUE_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_YELLOW_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_LIME_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_PINK_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAY_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_GRAY_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_CYAN_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPLE_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_BROWN_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_GREEN_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACK_WOOL;
    @OwnableTE @Reinforced public static Block REINFORCED_GOLD_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_IRON_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_OAK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SPRUCE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_BIRCH_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_JUNGLE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_ACACIA_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_OAK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_NORMAL_STONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_STONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_CUT_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_COBBLESTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_STONE_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHER_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_QUARTZ_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_CUT_RED_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPUR_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_PRISMARINE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_QUARTZ;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_RED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_STONE;
    @OwnableTE @Reinforced public static Block REINFORCED_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_BOOKSHELF;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_COBBLESTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_OBSIDIAN;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPUR_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPUR_PILLAR;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPUR_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_OAK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_DIAMOND_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_COBBLESTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_ICE;
    @OwnableTE @Reinforced public static Block REINFORCED_SNOW_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_CLAY;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHERRACK;
    @OwnableTE @Reinforced public static Block REINFORCED_SOUL_SOIL;
    @OwnableTE @Reinforced public static Block REINFORCED_BASALT;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BASALT;
    @OwnableTE @Reinforced public static Block REINFORCED_GLOWSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_STONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_STONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_CRACKED_STONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_STONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_STONE_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_MYCELIUM;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHER_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_CRACKED_NETHER_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_NETHER_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHER_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_END_STONE;
    @OwnableTE @Reinforced public static Block REINFORCED_END_STONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_SANDSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_EMERALD_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_SPRUCE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_BIRCH_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_JUNGLE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_CRIMSON_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_QUARTZ;
    @OwnableTE @Reinforced public static Block REINFORCED_QUARTZ;
    @OwnableTE @Reinforced public static Block REINFORCED_QUARTZ_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_QUARTZ_PILLAR;
    @OwnableTE @Reinforced public static Block REINFORCED_QUARTZ_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_WHITE_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_ORANGE_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_MAGENTA_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_BLUE_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_YELLOW_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_LIME_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_PINK_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAY_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_GRAY_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_CYAN_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPLE_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_BROWN_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_GREEN_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACK_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_TERRACOTTA;
    @OwnableTE @Reinforced public static Block REINFORCED_COAL_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_PACKED_ICE;
    @OwnableTE @Reinforced public static Block REINFORCED_ACACIA_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_OAK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_WHITE_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_ORANGE_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_MAGENTA_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_BLUE_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_YELLOW_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_LIME_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_PINK_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAY_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_GRAY_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_CYAN_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPLE_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_BROWN_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_GREEN_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACK_STAINED_GLASS;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_PRISMARINE;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_DARK_PRISMARINE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_SEA_LANTERN;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_RED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_CUT_RED_SANDSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_SANDSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHER_WART_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_WARPED_WART_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_NETHER_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_BONE_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_WHITE_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_ORANGE_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_MAGENTA_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_BLUE_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_YELLOW_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_LIME_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_PINK_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAY_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_GRAY_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_CYAN_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPLE_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_BROWN_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_GREEN_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACK_CONCRETE;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_ICE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_GRANITE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_RED_SANDSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_STONE_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_END_STONE_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_STONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_SANDSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_QUARTZ_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_GRANITE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_ANDESITE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_NETHER_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_ANDESITE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_DIORITE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_GRANITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_RED_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_STONE_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_DIORITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_COBBLESTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_END_STONE_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_SANDSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_SMOOTH_QUARTZ_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_GRANITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_ANDESITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_NETHER_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_ANDESITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_DIORITE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHERITE_BLOCK;
    @OwnableTE @Reinforced public static Block REINFORCED_CRYING_OBSIDIAN;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACKSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACKSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACKSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_PLOISHED_BLACKSTONE_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_CHISELED_POLISHED_BLACKSTONE;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_BRICKS;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_BRICK_SLAB;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_BRICK_STAIRS;
    @OwnableTE @Reinforced public static Block REINFORCED_CRACKED_POLISHED_BLACKSTONE_BRICKS;
    //ordered by vanilla decoration blocks creative tab order
    @OwnableTE @Reinforced public static Block REINFORCED_COBWEB;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_IRON_BARS;
    @OwnableTE @Reinforced public static Block REINFORCED_CHAIN;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_REINFORCED_GLASS_PANE;
    @OwnableTE @Reinforced public static Block REINFORCED_COBBLESTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_COBBLESTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_PRISMARINE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_SANDSTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_MOSSY_STONE_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_GRANITE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_STONE_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_NETHER_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_ANDESITE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_NETHER_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_SANDSTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_END_STONE_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_DIORITE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACKSTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_BRICK_WALL;
    @OwnableTE @Reinforced public static Block REINFORCED_WHITE_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_ORANGE_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_MAGENTA_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_BLUE_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_YELLOW_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_LIME_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_PINK_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_GRAY_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_LIGHT_GRAY_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_CYAN_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_PURPLE_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_BLUE_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_BROWN_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_GREEN_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_RED_CARPET;
    @OwnableTE @Reinforced public static Block REINFORCED_BLACK_CARPET;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_WHITE_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_ORANGE_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_MAGENTA_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_LIGHT_BLUE_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_YELLOW_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_LIME_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_PINK_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_GRAY_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_LIGHT_GRAY_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_CYAN_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_PURPLE_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_BLUE_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_BROWN_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_GREEN_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_RED_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_BLACK_STAINED_GLASS_PANE;
    @OwnableTE @Reinforced public static Block REINFORCED_LANTERN;
    @OwnableTE @Reinforced public static Block REINFORCED_SOUL_LANTERN;
    @OwnableTE @Reinforced public static Block REINFORCED_SHROOMLIGHT;

    //ordered by vanilla redstone tab order
    @HasManualPage @Reinforced public static Block REINFORCED_LEVER;
    @HasManualPage @Reinforced public static Block REINFORCED_STONE_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_OAK_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_SPRUCE_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_BIRCH_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_JUNGLE_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_ACACIA_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_DARK_OAK_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_CRIMSON_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_WARPED_PRESSURE_PLATE;
    @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_PRESSURE_PLATE;
    @OwnableTE @Reinforced public static Block REINFORCED_REDSTONE_LAMP;
    @HasManualPage @Reinforced public static Block REINFORCED_STONE_BUTTON;
    @Reinforced public static Block REINFORCED_OAK_BUTTON;
    @Reinforced public static Block REINFORCED_SPRUCE_BUTTON;
    @Reinforced public static Block REINFORCED_BIRCH_BUTTON;
    @Reinforced public static Block REINFORCED_JUNGLE_BUTTON;
    @Reinforced public static Block REINFORCED_ACACIA_BUTTON;
    @Reinforced public static Block REINFORCED_DARK_OAK_BUTTON;
    @Reinforced public static Block REINFORCED_CRIMSON_BUTTON;
    @Reinforced public static Block REINFORCED_WARPED_BUTTON;
    @Reinforced public static Block REINFORCED_POLISHED_BLACKSTONE_BUTTON;
    @OwnableTE @Reinforced public static Block REINFORCED_REDSTONE_BLOCK;
    @HasManualPage @Reinforced public static Block REINFORCED_HOPPER;
    @HasManualPage @OwnableTE @Reinforced(hasTint = false) public static Block REINFORCED_IRON_TRAPDOOR;
    @OwnableTE @Reinforced public static Block REINFORCED_OBSERVER;

    //misc
    @Reinforced(tint=0x0E7063) public static Block REINFORCED_CHISELED_CRYSTAL_QUARTZ;
    @Reinforced(tint=0x0E7063) public static Block REINFORCED_CRYSTAL_QUARTZ;
    @Reinforced(tint=0x0E7063) public static Block REINFORCED_CRYSTAL_QUARTZ_PILLAR;
    @Reinforced(tint=0x0E7063) public static Block REINFORCED_CRYSTAL_QUARTZ_SLAB;
    @Reinforced(tint=0x0E7063) public static Block REINFORCED_CRYSTAL_QUARTZ_STAIRS;
    @OwnableTE public static Block HORIZONTAL_REINFORCED_IRON_BARS;
    @OwnableTE @Reinforced public static Block REINFORCED_GRASS_PATH;

    //items
    @HasManualPage public static Item ADMIN_TOOL;
    public static Item ACIENT_DEBRIS_MINE_ITEM;
    @HasManualPage public static Item BRIEFCASE;
    @HasManualPage public static Item CAMERA_MONITOR;
    @HasManualPage public static Item CODEBREAKER;
    @HasManualPage public static Item CRYSTAL_QUARTZ_ITEM;
    @HasManualPage public static Item FAKE_LAVA_BUCKET;
    @HasManualPage public static Item FAKE_WATER_BUCKET;
    @HasManualPage public static Item KEYCARD_LVL_1;
    @HasManualPage public static Item KEYCARD_LVL_2;
    @HasManualPage public static Item KEYCARD_LVL_3;
    @HasManualPage public static Item KEYCARD_LVL_4;
    @HasManualPage public static Item KEYCARD_LVL_5;
    @HasManualPage public static Item KEY_PANEL;
    public static Item KEYPAD_CHEST_ITEM;
    @HasManualPage public static Item LIMITED_USE_KEYCARD;
    @HasManualPage public static Item REINFORCED_DOOR_ITEM;
    @HasManualPage public static Item REMOTE_ACCESS_MINE;
    @HasManualPage public static Item REMOTE_ACCESS_SENTRY;
    @HasManualPage public static Item SCANNER_DOOR_ITEM;
    @HasManualPage public static Item SC_MANUAL;
    @HasManualPage public static Item SECRET_OAK_SIGN_ITEM;
    public static Item SECRET_SPRUCE_SIGN_ITEM;
    public static Item SECRET_BIRCH_SIGN_ITEM;
    public static Item SECRET_JUNGLE_SIGN_ITEM;
    public static Item SECRET_ACACIA_SIGN_ITEM;
    public static Item SECRET_DARK_OAK_SIGN_ITEM;
    public static Item SECRET_CRIMSON_SIGN_ITEM;
    public static Item SECRET_WARPED_SIGN_ITEM;
    @HasManualPage(designedBy="Henzoid") public static Item SENTRY;
    @HasManualPage public static Item TASER;
    public static Item TASER_POWERED;
    @HasManualPage public static Item UNIVERSAL_BLOCK_MODIFIER;
    @HasManualPage public static Item UNIVERSAL_BLOCK_REINFORCER_LVL_1;
    @HasManualPage public static Item UNIVERSAL_BLOCK_REINFORCER_LVL_2;
    @HasManualPage public static Item UNIVERSAL_BLOCK_REINFORCER_LVL_3;
    @HasManualPage public static Item UNIVERSAL_BLOCK_REMOVER;
    @HasManualPage public static Item UNIVERSAL_KEY_CHANGER;
    @HasManualPage public static Item UNIVERSAL_OWNER_CHANGER;
    @HasManualPage public static Item WIRE_CUTTERS;

    //modules
    @HasManualPage public static ModuleItem BLACKLIST_MODULE;
    @HasManualPage public static ModuleItem DISGUISE_MODULE;
    @HasManualPage public static ModuleItem HARMING_MODULE;
    @HasManualPage public static ModuleItem REDSTONE_MODULE;
    @HasManualPage public static ModuleItem SMART_MODULE;
    @HasManualPage public static ModuleItem STORAGE_MODULE;
    @HasManualPage public static ModuleItem WHITELIST_MODULE;

    //tile entity types
    public static BlockEntityType<OwnableTileEntity> teTypeOwnable;
    public static BlockEntityType<SecurityCraftTileEntity> teTypeAbstract;
    public static BlockEntityType<KeypadTileEntity> teTypeKeypad;
    public static BlockEntityType<LaserBlockTileEntity> teTypeLaserBlock;
    public static BlockEntityType<CageTrapTileEntity> teTypeCageTrap;
    public static BlockEntityType<KeycardReaderTileEntity> teTypeKeycardReader;
    public static BlockEntityType<InventoryScannerTileEntity> teTypeInventoryScanner;
    public static BlockEntityType<PortableRadarTileEntity> teTypePortableRadar;
    public static BlockEntityType<SecurityCameraTileEntity> teTypeSecurityCamera;
    public static BlockEntityType<UsernameLoggerTileEntity> teTypeUsernameLogger;
    public static BlockEntityType<RetinalScannerTileEntity> teTypeRetinalScanner;
    public static BlockEntityType<KeypadChestTileEntity> teTypeKeypadChest;
    public static BlockEntityType<AlarmTileEntity> teTypeAlarm;
    public static BlockEntityType<ClaymoreTileEntity> teTypeClaymore;
    public static BlockEntityType<KeypadFurnaceTileEntity> teTypeKeypadFurnace;
    public static BlockEntityType<IMSTileEntity> teTypeIms;
    public static BlockEntityType<ProtectoTileEntity> teTypeProtecto;
    public static BlockEntityType<ScannerDoorTileEntity> teTypeScannerDoor;
    public static BlockEntityType<SecretSignTileEntity> teTypeSecretSign;
    public static BlockEntityType<MotionActivatedLightTileEntity> teTypeMotionLight;
    public static BlockEntityType<TrackMineTileEntity> teTypeTrackMine;
    public static BlockEntityType<TrophySystemTileEntity> teTypeTrophySystem;
    public static BlockEntityType<BlockPocketManagerTileEntity> teTypeBlockPocketManager;
    public static BlockEntityType<BlockPocketTileEntity> teTypeBlockPocket;
    public static BlockEntityType<WhitelistOnlyTileEntity> teTypeWhitelistOnly;
    public static BlockEntityType<ReinforcedHopperTileEntity> teTypeReinforcedHopper;
    public static BlockEntityType<ProjectorTileEntity> teTypeProjector;

    //entity types
    public static EntityType<BouncingBettyEntity> eTypeBouncingBetty;
    public static EntityType<IMSBombEntity> eTypeImsBomb;
    public static EntityType<SecurityCameraEntity> eTypeSecurityCamera;
    public static EntityType<SentryEntity> eTypeSentry;
    public static EntityType<BulletEntity> eTypeBullet;

    //container types
    public static ScreenHandlerType<BlockReinforcerContainer> cTypeBlockReinforcer;
    public static ScreenHandlerType<GenericContainer> cTypeBriefcase;
    public static ScreenHandlerType<BriefcaseContainer> cTypeBriefcaseInventory;
    public static ScreenHandlerType<GenericContainer> cTypeBriefcaseSetup;
    public static ScreenHandlerType<CustomizeBlockContainer> cTypeCustomizeBlock;
    //public static ScreenHandlerType<DisguiseModuleContainer> cTypeDisguiseModule;
    public static ScreenHandlerType<InventoryScannerContainer> cTypeInventoryScanner;
    public static ScreenHandlerType<KeypadFurnaceContainer> cTypeKeypadFurnace;
    public static ScreenHandlerType<ProjectorContainer> cTypeProjector;
    public static ScreenHandlerType<GenericTEContainer> cTypeCheckPassword;
    public static ScreenHandlerType<GenericTEContainer> cTypeSetPassword;
    public static ScreenHandlerType<GenericTEContainer> cTypeUsernameLogger;
    public static ScreenHandlerType<GenericTEContainer> cTypeIMS;
    public static ScreenHandlerType<GenericTEContainer> cTypeKeycardSetup;
    public static ScreenHandlerType<GenericTEContainer> cTypeKeyChanger;
    public static ScreenHandlerType<GenericTEContainer> cTypeBlockPocketManager;
}
